# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parseFeatureXMLFile <- function(file) {
    .Call(`_patRoon_parseFeatureXMLFile`, file)
}

parseFeatConsXMLFile <- function(file, anaCount) {
    .Call(`_patRoon_parseFeatConsXMLFile`, file, anaCount)
}

writeFeatureXML <- function(featList, out) {
    invisible(.Call(`_patRoon_writeFeatureXML`, featList, out))
}

specDistMatrix <- function(specList, method, shift, precMZs, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_specDistMatrix`, specList, method, shift, precMZs, mzWeight, intWeight, mzWindow)
}

loadEICIntensities <- function(spectra, featList, rtWindow) {
    .Call(`_patRoon_loadEICIntensities`, spectra, featList, rtWindow)
}

loadEICs <- function(spectra, rtRanges, mzRanges) {
    .Call(`_patRoon_loadEICs`, spectra, rtRanges, mzRanges)
}

binSpecCPP <- function(sp1, sp2, shift, mzWindow) {
    .Call(`_patRoon_binSpecCPP`, sp1, sp2, shift, mzWindow)
}

calcSpecSimilarity <- function(sp1, sp2, method, shift, precDiff, mzWeight, intWeight, mzWindow) {
    .Call(`_patRoon_calcSpecSimilarity`, sp1, sp2, method, shift, precDiff, mzWeight, intWeight, mzWindow)
}

